version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: fas
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  # fastapi:
  #   build: ./fastapi
  #   container_name: fastapi
  #   ports:
  #     - 8000:8000
  #   tty: true
  #   volumes:
  #     - ./fastapi:/fastapi

  #   command: uvicorn main:app --reload --host=0.0.0.0

  sf:
    build: ./sf
    container_name: sf_c
    ports:
      - 5000:5000
    tty: true
    environment:
      FLASK_APP: "${FLASK_APP}"
      FLASK_ENV: "${FLASK_ENV}"
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}

    volumes:
      - ./sf:/app
    
    command: flask run --host=0.0.0.0

  customer:
    build: ./customer
    container_name: customer_c
    ports:
      - 50000:5000
    tty: true
    environment:
      FLASK_APP: "${FLASK_APP}"
      FLASK_ENV: "${FLASK_ENV}"
    volumes:
      - ./customer:/app
    command: flask run --host=0.0.0.0

  shipping:
    build: ./shipping
    container_name: shipping
    ports:
      - 55000:5000
    tty: true
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}

    volumes:
      - ./shipping:/app

    command: flask run --host=0.0.0.0
